# Generated by Django 6.0.2 on 2026-03-04 06:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_companyuser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='classification name')),
                ('internal_path', models.CharField(db_index=True, help_text='System-generated. Do not edit manually.', max_length=500, verbose_name='internal path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='companies.company', verbose_name='company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chartofaccounts.accountclassification', verbose_name='parent classification')),
            ],
            options={
                'verbose_name': 'account classification',
                'verbose_name_plural': 'account classifications',
                'ordering': ['internal_path'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='account name')),
                ('code', models.CharField(max_length=30, verbose_name='account code')),
                ('internal_path', models.CharField(db_index=True, help_text='System-generated. Do not edit manually.', max_length=500, verbose_name='internal path')),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6, verbose_name='normal balance')),
                ('currency', models.CharField(help_text='Defaults to company base currency. Cannot change after first transaction.', max_length=3, verbose_name='currency')),
                ('is_system_account', models.BooleanField(default=False, verbose_name='system account')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='deletable')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_accounts', to='chartofaccounts.account', verbose_name='parent account')),
                ('classification', models.ForeignKey(help_text='The Layer 3 classification group this account belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='chartofaccounts.accountclassification', verbose_name='classification (Layer 3)')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['internal_path'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_code', models.CharField(help_text='Internal identifier used by ERP modules.', max_length=50, verbose_name='system code')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_mappings', to='chartofaccounts.account', verbose_name='mapped account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_account_mappings', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'system account mapping',
                'verbose_name_plural': 'system account mappings',
            },
        ),
        migrations.AddConstraint(
            model_name='accountclassification',
            constraint=models.UniqueConstraint(fields=('company', 'internal_path'), name='unique_classification_path_per_company'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='idx_account_company_active'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'classification'], name='idx_account_company_class'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_account_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'internal_path'), name='unique_account_path_per_company'),
        ),
        migrations.AddConstraint(
            model_name='systemaccountmapping',
            constraint=models.UniqueConstraint(fields=('company', 'system_code'), name='unique_system_code_per_company'),
        ),
    ]
