# Generated by Django 6.0.2 on 2026-03-05 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccounts', '0001_initial'),
        ('companies', '0002_alter_companyuser_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'classification', 'name'), name='unique_active_account_name_per_classification'),
        ),
    ]
