# Generated by Django 6.0.2 on 2026-03-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccounts', '0002_account_unique_active_account_name_per_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(help_text='The Layer 3 classification group this account belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='chartofaccounts.accountclassification', verbose_name='classification (Layer 3)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='chartofaccounts.account', verbose_name='parent account'),
        ),
        migrations.AlterField(
            model_name='systemaccountmapping',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_mappings', to='chartofaccounts.account', verbose_name='mapped account'),
        ),
    ]
