# Generated by Django 6.0.2 on 2026-03-24 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccounts', '0003_alter_account_classification_and_more'),
        ('companies', '0003_company_lock_date_company_reporting_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_active_account_name_per_classification',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'name'), name='unique_active_account_name_per_company'),
        ),
    ]
