/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/forgot-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Step 1 of password reset. Accepts an email, generates a 6-digit OTP,
         *     stores it on the User with an expiry, and emails the OTP via the
         *     centralized email service.
         *
         *     RESPONSE BEHAVIOUR — INTENTIONALLY OPAQUE:
         *         We always return HTTP 200 with the same message whether the email
         *         belongs to a real user or not. Returning a distinguishable error
         *         would let attackers enumerate valid emails with a wordlist. Also
         *         matches the existing ResendOTPView pattern.
         */
        post: operations["auth_forgot_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-otp/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_resend_otp_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Step 2 of password reset. Validates the OTP and, on success, updates
         *     the password and terminates every existing session for the user.
         *
         *     FORCED LOGOUT ON SUCCESS:
         *         Every refresh token belonging to the user is blacklisted. This is
         *         critical: if the reset was triggered because the account was
         *         compromised, we must eject the attacker even if they currently hold
         *         a valid access token. Note that access tokens live up to
         *         ACCESS_TOKEN_LIFETIME (24h in this project); the attacker could
         *         still use an existing access token until it expires, but they
         *         cannot refresh it, so the window is bounded.
         */
        post: operations["auth_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all companies the logged-in user is a member of.
         *
         *     N+1 FIX: Instead of using SerializerMethodField (which queries per company),
         *     we fetch all memberships in ONE query and inject the role into each company
         *     object before serialization. This means 1 query instead of N+1.
         */
        get: operations["companies_retrieve"];
        put?: never;
        post: operations["companies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["companies_retrieve_2"];
        put: operations["companies_update"];
        post?: never;
        /**
         * @description Soft-delete a company. OWNER only.
         *     Sets is_active=False — preserves all data but hides the company.
         */
        delete: operations["companies_destroy"];
        options?: never;
        head?: never;
        patch: operations["companies_partial_update"];
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/companies/<id>/accounts/
         *         → List all accounts with optional filtering
         *
         *     POST /api/companies/<id>/accounts/
         *         → Create a new account
         */
        get: operations["companies_accounts_retrieve"];
        put?: never;
        /**
         * @description GET  /api/companies/<id>/accounts/
         *         → List all accounts with optional filtering
         *
         *     POST /api/companies/<id>/accounts/
         *         → Create a new account
         */
        post: operations["companies_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/{account_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET   /api/companies/<id>/accounts/<account_id>/
         *     PATCH /api/companies/<id>/accounts/<account_id>/
         */
        get: operations["companies_accounts_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description GET   /api/companies/<id>/accounts/<account_id>/
         *     PATCH /api/companies/<id>/accounts/<account_id>/
         */
        patch: operations["companies_accounts_partial_update"];
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/{account_id}/activate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/companies/<id>/accounts/<account_id>/activate/ */
        post: operations["companies_accounts_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/{account_id}/balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET → Calculate and return the current balance of an account.
         *     Supports ?as_of_date=YYYY-MM-DD and ?include_sub_accounts=true/false.
         */
        get: operations["companies_accounts_balance_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/{account_id}/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/companies/<id>/accounts/<account_id>/deactivate/ */
        post: operations["companies_accounts_deactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/accounts/{account_id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description WHY A SEPARATE URL?
         *     We use /delete/ instead of just DELETE on /accounts/<id>/ because
         *     delete is a destructive, permanent action. Having a separate URL
         *     makes it harder to accidentally trigger from the frontend. The
         *     detail endpoint (PATCH) and the delete endpoint are separated.
         */
        delete: operations["companies_accounts_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/chart-of-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/companies/<id>/chart-of-accounts/ */
        get: operations["companies_chart_of_accounts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/classifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET  /api/companies/<id>/classifications/
         *         → List all classifications
         *
         *     POST /api/companies/<id>/classifications/
         *         → Create classification
         */
        get: operations["companies_classifications_retrieve"];
        put?: never;
        /**
         * @description GET  /api/companies/<id>/classifications/
         *         → List all classifications
         *
         *     POST /api/companies/<id>/classifications/
         *         → Create classification
         */
        post: operations["companies_classifications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List journal entries with optional filters.
         *
         *     PERFORMANCE:
         *         The queryset carries two annotations (`total_amount`, `line_count`)
         *         consumed by ManualJournalListSerializer. This replaces an older
         *         implementation that computed these via SerializerMethodField per
         *         row, causing a 2×N N+1 query pattern. See the serializer docstring
         *         for details.
         *
         *         We also drop prefetch_related('lines') from the list path: the list
         *         serializer no longer reads line rows directly — only the aggregated
         *         annotations — so prefetching lines would be wasted work and memory.
         */
        get: operations["companies_journal_entries_retrieve"];
        put?: never;
        /**
         * @description GET  → List journal entries with optional filters
         *     POST → Create a new journal entry (DRAFT)
         */
        post: operations["companies_journal_entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/{entry_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET    → View journal details with all lines
         *     PATCH  → Edit a draft journal
         *     DELETE → Delete a draft journal
         */
        get: operations["companies_journal_entries_retrieve_2"];
        put?: never;
        post?: never;
        /**
         * @description GET    → View journal details with all lines
         *     PATCH  → Edit a draft journal
         *     DELETE → Delete a draft journal
         */
        delete: operations["companies_journal_entries_destroy"];
        options?: never;
        head?: never;
        /**
         * @description GET    → View journal details with all lines
         *     PATCH  → Edit a draft journal
         *     DELETE → Delete a draft journal
         */
        patch: operations["companies_journal_entries_partial_update"];
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/{entry_id}/post/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST → Post a draft journal entry (DRAFT → POSTED). */
        post: operations["companies_journal_entries_post_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/{entry_id}/void/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST → Void a posted journal entry (POSTED → VOID). */
        post: operations["companies_journal_entries_void_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/bulk-import/template/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/<id>/journal-entries/bulk-import/template/
         *
         *     Download the bulk import Excel template, pre-populated with
         *     this company's account reference sheet.
         */
        get: operations["companies_journal_entries_bulk_import_template_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/bulk-import/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description POST /api/companies/<id>/journal-entries/bulk-import/upload/
         *
         *     Upload a filled bulk import file (.xlsx or .csv).
         *
         *     Form data:
         *         file: The uploaded file
         *         save_mode: "valid_only" or "all_or_none" (default: "all_or_none")
         *
         *     "valid_only":  Save accepted entries, return rejected with errors.
         *     "all_or_none": If ANY entry fails, save nothing, return all errors.
         *
         *     All imported entries are created as DRAFT.
         */
        post: operations["companies_journal_entries_bulk_import_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/journal-entries/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/<company_id>/journal-entries/export/
         *
         *     Export all journal entries matching the filters as xlsx / csv / pdf / docx.
         *
         *     QUERY PARAMS:
         *         export        — xlsx | csv | pdf | docx       REQUIRED
         *         status        — DRAFT | POSTED | VOID         optional
         *         journal_type  — ADJUSTMENT | SALES | ...      optional
         *         date_from     — YYYY-MM-DD                    optional
         *         date_to       — YYYY-MM-DD                    optional
         *         search        — free text                     optional
         *
         *     WHY A DEDICATED VIEW (instead of ?export= on the list endpoint):
         *         - Cleaner OpenAPI schema (the list endpoint stays strictly JSON).
         *         - No pagination ambiguity — export always returns everything matching
         *           the filter, pagination only applies to the human-facing list UI.
         *         - Shares the same filter surface as the list endpoint, so there is
         *           no new vocabulary for users to learn.
         *
         *     PERMISSIONS:
         *         Same as list: any JOURNAL_VIEW_ROLES member (OWNER, ADMIN,
         *         ACCOUNTANT, AUDITOR). Export is a read operation.
         *
         *     RATE LIMIT:
         *         Not throttled at the per-endpoint level yet. If abuse emerges,
         *         add a scoped throttle keyed by user_id (authenticated users only —
         *         this endpoint is not AllowAny).
         */
        get: operations["companies_journal_entries_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all active members and pending invitations. */
        get: operations["companies_members_retrieve"];
        put?: never;
        post: operations["companies_members_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/members/{member_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Remove a member from the company (soft delete). OWNER or ADMIN only. */
        delete: operations["companies_members_destroy"];
        options?: never;
        head?: never;
        /** @description Update a member's role. OWNER or ADMIN only. */
        patch: operations["companies_members_partial_update"];
        trace?: never;
    };
    "/api/companies/{company_id}/reports/account-transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/account-transactions/
         *
         *     Generates a detailed Account Transactions report for a single
         *     account. This is the drill-down view — when a user clicks an
         *     account name in Trial Balance, Balance Sheet, P&L, or General
         *     Ledger, they land here.
         *
         *     Shows every ledger entry with opening balance, running balance,
         *     closing balance, and source journal references (entry_number,
         *     description, reference).
         *
         *     NO PAGINATION — all entries in the date range are returned.
         *     Date range filtering naturally bounds the data volume.
         *
         *     Query Parameters:
         *         account_id      UUID (REQUIRED — the account to show)
         *         from_date       YYYY-MM-DD (default: fiscal year start)
         *         to_date         YYYY-MM-DD (default: today)
         */
        get: operations["companies_reports_account_transactions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/reports/balance-sheet/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/balance-sheet/
         *
         *     Generates a Balance Sheet (Statement of Financial Position).
         *     Shows Assets = Liabilities + Equity at a specific date.
         *
         *     Automatically calculates retained earnings from Income − Expense
         *     accounts. Supports both auto-calculation and manual closing journals
         *     without double-counting.
         *
         *     Query Parameters:
         *         as_of_date      YYYY-MM-DD (default: today)
         *         filter_mode     'all' | 'with_transactions' | 'non_zero' (default)
         *         compare_date    YYYY-MM-DD (optional comparison column)
         */
        get: operations["companies_reports_balance_sheet_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/reports/cash-flow/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/cash-flow/
         *
         *     Generates a Cash Flow Statement.
         *     Shows where cash came from and where it went during a period,
         *     split into Operating, Investing, and Financing activities.
         *
         *     Period-based report (like Income Statement).
         *     Default period: fiscal year start → today.
         *
         *     Query Parameters:
         *         method              'indirect' (default) | 'direct'
         *         from_date           YYYY-MM-DD (default: fiscal year start)
         *         to_date             YYYY-MM-DD (default: today)
         *         compare_from_date   YYYY-MM-DD (optional comparison period start)
         *         compare_to_date     YYYY-MM-DD (optional comparison period end)
         */
        get: operations["companies_reports_cash_flow_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/reports/general-ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/general-ledger/
         *
         *     Generates a detailed General Ledger showing every transaction
         *     per account with opening balance, running balance, and closing
         *     balance. This is the transaction-level detail report.
         *
         *     Unlike the summary reports (Trial Balance, Balance Sheet, Income
         *     Statement), this shows individual LedgerEntry rows.
         *
         *     Query Parameters:
         *         from_date       YYYY-MM-DD (default: fiscal year start)
         *         to_date         YYYY-MM-DD (default: today)
         *         account_id      UUID (optional — filter to a single account)
         *         journal_type    str (optional — filter by type: SALES, PURCHASE, etc.)
         *
         *     PAGINATION:
         *         Paginated at the account level — each page contains N complete
         *         accounts with all their transactions. Default page_size=20 accounts.
         *         Use ?page=2&page_size=10 to control.
         */
        get: operations["companies_reports_general_ledger_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/reports/income-statement/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/income-statement/
         *
         *     Generates an Income Statement (Profit & Loss).
         *     Shows Revenue − Expenses = Net Income for a specific PERIOD.
         *
         *     Unlike the Balance Sheet (point-in-time), this is period-based.
         *     Default period: fiscal year start → today (Year-to-Date).
         *
         *     Query Parameters:
         *         from_date           YYYY-MM-DD (default: fiscal year start)
         *         to_date             YYYY-MM-DD (default: today)
         *         filter_mode         'all' | 'with_transactions' | 'non_zero' (default)
         *         compare_from_date   YYYY-MM-DD (optional comparison period start)
         *         compare_to_date     YYYY-MM-DD (optional comparison period end)
         *
         *     COMPARISON NOTES:
         *         Both compare_from_date and compare_to_date must be provided
         *         together. Typical use cases:
         *         - This month vs last month
         *         - This quarter vs same quarter last year
         *         - YTD this year vs YTD last year
         */
        get: operations["companies_reports_income_statement_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/reports/trial-balance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/{company_id}/reports/trial-balance/
         *
         *     Query Parameters:
         *         as_of_date      YYYY-MM-DD (default: today)
         *         filter_mode     'all' | 'with_transactions' | 'non_zero' (default)
         *         compare_date    YYYY-MM-DD (optional comparison column)
         *         layout          'nested' (default) | 'flat'
         */
        get: operations["companies_reports_trial_balance_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/system-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/companies/<id>/system-accounts/ */
        get: operations["companies_system_accounts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/transfer-ownership/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["companies_transfer_ownership_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/custom-coa-template/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/companies/custom-coa-template/download/
         *
         *     Returns a downloadable Excel template for custom Chart of Accounts.
         *
         *     The template has 4 sheets:
         *     - Instructions: Rules, field reference, and the list of 43 system accounts
         *     - Default CoA Tree: Complete visual tree of the 104-account default CoA
         *     - Classifications: Layer 3 groups (system + custom)
         *     - Accounts: Layer 4 accounts (system + custom)
         *
         *     The user fills in the template and uploads it during company creation.
         *
         *     WHY HttpResponse INSTEAD OF Response?
         *         DRF's Response is designed for JSON data. For file downloads,
         *         we use Django's HttpResponse directly because it lets us set
         *         the content_type to the Excel MIME type and add the
         *         Content-Disposition header that triggers a download in the browser.
         */
        get: operations["companies_custom_coa_template_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_forgot_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_resend_otp_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_balance_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_deactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_accounts_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_chart_of_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_classifications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_classifications_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_post_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_void_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_bulk_import_template_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_bulk_import_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_journal_entries_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_members_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_members_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_account_transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_balance_sheet_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_cash_flow_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_general_ledger_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_income_statement_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_reports_trial_balance_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_system_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_transfer_ownership_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    companies_custom_coa_template_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
