# backend/journals/admin.py

from django.contrib import admin, messages
from django.urls import reverse
from django.utils.html import format_html
from django.utils.safestring import mark_safe

from .models import ManualJournal, ManualJournalLine, LedgerEntry
from .services import post_journal, void_journal


class ManualJournalLineInline(admin.TabularInline):
    model = ManualJournalLine
    extra = 0
    readonly_fields = ('id', 'account', 'entry_type', 'amount', 'tax_profile', 'description', 'created_at')
    fields = ('account', 'entry_type', 'amount', 'tax_profile', 'description', 'created_at')

    def has_add_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False


class LedgerEntryInlineForJournal(admin.TabularInline):
    """Show ledger entries generated by this journal (read-only)."""
    model = LedgerEntry
    fk_name = None  # Cannot use regular FK — using GenericFK
    extra = 0

    # We can't use a normal inline for GenericFK, so we show them
    # via a custom method on the ManualJournalAdmin instead.


# ══════════════════════════════════════════════════
# ADMIN ACTIONS — BULK POST & BULK VOID
# ══════════════════════════════════════════════════

@admin.action(description='Post selected DRAFT journals')
def bulk_post_journals(modeladmin, request, queryset):
    """
    Admin action: Select one or more DRAFT journals and post them.

    Calls the same post_journal() service used by the API endpoint,
    so all validation (lock date, balance check) is enforced.
    Journals that are not DRAFT are skipped with a warning.

    Uses request.user as the posted_by user for audit trail.
    """
    posted_count = 0
    skipped_count = 0
    error_messages = []

    for journal in queryset.select_related('company'):
        # ── Skip non-DRAFT journals ──
        if journal.status != 'DRAFT':
            skipped_count += 1
            error_messages.append(
                f'{journal.entry_number}: Skipped — status is '
                f'{journal.get_status_display()}, not DRAFT.'
            )
            continue

        # ── Attempt to post via the service layer ──
        try:
            post_journal(journal, posted_by=request.user)
            posted_count += 1
        except ValueError as e:
            skipped_count += 1
            error_messages.append(
                f'{journal.entry_number}: Failed — {str(e)}'
            )

    # ── Report results to admin ──
    if posted_count:
        modeladmin.message_user(
            request,
            f'Successfully posted {posted_count} journal(s).',
            messages.SUCCESS,
        )
    if skipped_count:
        # Show each skip/error reason as a separate warning
        for msg in error_messages:
            modeladmin.message_user(request, msg, messages.WARNING)


@admin.action(description='Void selected POSTED journals (create reversals)')
def bulk_void_journals(modeladmin, request, queryset):
    """
    Admin action: Select one or more POSTED journals and void them.

    Calls the same void_journal() service used by the API endpoint,
    so all validation (lock date, already voided) is enforced.
    Journals that are not POSTED are skipped with a warning.

    The void_date defaults to today (same as the API behaviour).
    Uses request.user as the voided_by user for audit trail.
    """
    voided_count = 0
    skipped_count = 0
    error_messages = []

    for journal in queryset.select_related('company'):
        # ── Skip non-POSTED journals ──
        if journal.status != 'POSTED':
            skipped_count += 1
            error_messages.append(
                f'{journal.entry_number}: Skipped — status is '
                f'{journal.get_status_display()}, not POSTED.'
            )
            continue

        # ── Attempt to void via the service layer ──
        try:
            reversal = void_journal(
                journal,
                voided_by=request.user,
                void_date=None,  # Defaults to today inside the service
            )
            voided_count += 1
        except ValueError as e:
            skipped_count += 1
            error_messages.append(
                f'{journal.entry_number}: Failed — {str(e)}'
            )

    # ── Report results to admin ──
    if voided_count:
        modeladmin.message_user(
            request,
            f'Successfully voided {voided_count} journal(s). '
            f'Reversing entries have been created.',
            messages.SUCCESS,
        )
    if skipped_count:
        for msg in error_messages:
            modeladmin.message_user(request, msg, messages.WARNING)


# ══════════════════════════════════════════════════
# MANUAL JOURNAL ADMIN
# ══════════════════════════════════════════════════

@admin.register(ManualJournal)
class ManualJournalAdmin(admin.ModelAdmin):
    list_display = (
        'entry_number', 'company', 'date', 'status',
        'journal_type', 'currency', 'exchange_rate',
        'created_by', 'created_at',
    )
    list_filter = ('status', 'journal_type', 'company', 'currency')
    search_fields = ('entry_number', 'description', 'reference')
    ordering = ('-date', '-created_at')
    readonly_fields = (
        'id', 'company', 'entry_number', 'status', 'currency',
        'exchange_rate', 'date', 'description', 'reference',
        'journal_type',
        'posted_at', 'voided_at', 'voided_by',
        'voided_by_entry_link', 'reversal_of_link',
        'created_by', 'created_at', 'updated_at',
        'ledger_entries_summary',
    )
    inlines = [ManualJournalLineInline]

    # ── Register the bulk actions ──
    actions = [bulk_post_journals, bulk_void_journals]

    # ── Prevent creating journals from admin ──
    def has_add_permission(self, request):
        """
        Disable the 'Add' button in admin.
        Journals must be created via the API where double-entry
        validation, lock date checks, and entry numbering are enforced.
        """
        return False

    # ── Prevent deleting posted/void journals from admin ──
    def has_delete_permission(self, request, obj=None):
        if obj and obj.status != 'DRAFT':
            return False
        return super().has_delete_permission(request, obj)

    fieldsets = (
        ('Journal Header', {
            'fields': (
                'id', 'company', 'entry_number', 'date',
                'description', 'reference', 'journal_type', 'status',
            ),
        }),
        ('Currency', {
            'fields': ('currency', 'exchange_rate'),
        }),
        ('Void / Reversal', {
            'fields': (
                'voided_by_entry_link', 'reversal_of_link',
                'voided_by', 'posted_at', 'voided_at',
            ),
            'classes': ('collapse',),
        }),
        ('Ledger Impact', {
            'fields': ('ledger_entries_summary',),
        }),
        ('Audit', {
            'fields': ('created_by', 'created_at', 'updated_at'),
            'classes': ('collapse',),
        }),
    )

    def voided_by_entry_link(self, obj):
        if obj.voided_by_entry:
            url = reverse('admin:journals_manualjournal_change', args=[obj.voided_by_entry.pk])
            return format_html(
                '<a href="{}">{}</a>',
                url, obj.voided_by_entry.entry_number,
            )
        return '—'
    voided_by_entry_link.short_description = 'Voided by entry'

    def reversal_of_link(self, obj):
        if obj.reversal_of:
            url = reverse('admin:journals_manualjournal_change', args=[obj.reversal_of.pk])
            return format_html(
                '<a href="{}">{}</a>',
                url, obj.reversal_of.entry_number,
            )
        return '—'
    reversal_of_link.short_description = 'Reversal of'

    def ledger_entries_summary(self, obj):
        """Show all ledger entries generated from this journal's lines."""
        from django.contrib.contenttypes.models import ContentType
        ct = ContentType.objects.get_for_model(ManualJournalLine)
        line_ids = obj.lines.values_list('id', flat=True)
        entries = LedgerEntry.objects.filter(
            content_type=ct,
            object_id__in=line_ids,
        ).select_related('ledger_account').order_by('date', 'created_at')

        if not entries.exists():
            return 'No ledger entries (journal is still DRAFT).'

        rows = []
        for e in entries:
            url = reverse('admin:journals_ledgerentry_change', args=[e.pk])
            rows.append(
                f'<tr>'
                f'<td>{e.date}</td>'
                f'<td><a href="{url}">{e.ledger_account.code} — {e.ledger_account.name}</a></td>'
                f'<td>{e.entry_type}</td>'
                f'<td>{e.amount} {e.currency}</td>'
                f'<td>{e.base_amount} (base)</td>'
                f'</tr>'
            )
        table = (
            '<table style="border-collapse:collapse;width:100%">'
            '<tr style="background:#f0f0f0;font-weight:bold">'
            '<td style="padding:4px 8px">Date</td>'
            '<td style="padding:4px 8px">Account</td>'
            '<td style="padding:4px 8px">Dr/Cr</td>'
            '<td style="padding:4px 8px">Amount</td>'
            '<td style="padding:4px 8px">Base Amount</td>'
            '</tr>' + ''.join(rows) + '</table>'
        )
        return mark_safe(table)
    ledger_entries_summary.short_description = 'Ledger entries'


@admin.register(LedgerEntry)
class LedgerEntryAdmin(admin.ModelAdmin):
    list_display = (
        'date', 'ledger_account', 'entry_type', 'amount',
        'currency', 'base_amount', 'source_module',
        'journal_type', 'source_journal_link',
    )
    list_filter = (
        'company',
        ('ledger_account', admin.RelatedOnlyFieldListFilter),  # ← Shows only accounts that have entries
        'source_module',
        'journal_type',
        'entry_type',
    )
    search_fields = (
        'note',
        'ledger_account__name',
        'ledger_account__code',
    )
    ordering = ('-date', '-created_at')
    readonly_fields = (
        'id', 'content_type', 'object_id',
        'source_journal_link', 'created_at',
    )
    autocomplete_fields = ['ledger_account']

    fieldsets = (
        ('Ledger Entry', {
            'fields': (
                'id', 'company', 'ledger_account', 'date',
                'entry_type', 'amount', 'currency',
                'exchange_rate', 'base_amount', 'note',
            ),
        }),
        ('Source', {
            'fields': (
                'source_module', 'journal_type',
                'source_journal_link', 'content_type', 'object_id',
            ),
        }),
        ('Audit', {
            'fields': ('created_at',),
            'classes': ('collapse',),
        }),
    )

    def source_journal_link(self, obj):
        """Navigate back to the source ManualJournal."""
        try:
            source_line = obj.source_line
            if source_line and hasattr(source_line, 'journal'):
                journal = source_line.journal
                url = reverse(
                    'admin:journals_manualjournal_change',
                    args=[journal.pk],
                )
                return format_html(
                    '<a href="{}">{} — {}</a>',
                    url, journal.entry_number, journal.description[:50],
                )
        except Exception:
            pass
        return '—'
    source_journal_link.short_description = 'Source journal'

    def has_add_permission(self, request):
        """Ledger entries are system-generated. Cannot create manually."""
        return False

    def has_change_permission(self, request, obj=None):
        """Ledger entries are immutable after creation."""
        return False

    def has_delete_permission(self, request, obj=None):
        """Ledger entries cannot be deleted. Void the source journal instead."""
        return False