# Generated by Django 6.0.2 on 2026-02-23 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='company ID')),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('trade_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='trade name')),
                ('industry', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('TRADING', 'Trading / Wholesale / Retail'), ('SERVICES', 'Services / Consulting'), ('CONSTRUCTION', 'Construction / Real Estate'), ('HEALTHCARE', 'Healthcare / Pharmaceuticals'), ('IT_SOFTWARE', 'IT / Software / Technology'), ('AGRICULTURE', 'Agriculture / Farming'), ('EDUCATION', 'Education'), ('HOSPITALITY', 'Hospitality / Food & Beverage'), ('TRANSPORTATION', 'Transportation / Logistics'), ('OTHER', 'Other')], max_length=50, verbose_name='industry')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='BIN / Tax ID')),
                ('base_currency', models.CharField(choices=[('AED', 'AED — UAE Dirham'), ('AFN', 'AFN — Afghan Afghani'), ('ALL', 'ALL — Albanian Lek'), ('AMD', 'AMD — Armenian Dram'), ('ANG', 'ANG — Netherlands Antillean Guilder'), ('AOA', 'AOA — Angolan Kwanza'), ('ARS', 'ARS — Argentine Peso'), ('AUD', 'AUD — Australian Dollar'), ('AWG', 'AWG — Aruban Florin'), ('AZN', 'AZN — Azerbaijani Manat'), ('BAM', 'BAM — Bosnia Convertible Mark'), ('BBD', 'BBD — Barbadian Dollar'), ('BDT', 'BDT — Bangladeshi Taka'), ('BGN', 'BGN — Bulgarian Lev'), ('BHD', 'BHD — Bahraini Dinar'), ('BIF', 'BIF — Burundian Franc'), ('BMD', 'BMD — Bermudian Dollar'), ('BND', 'BND — Brunei Dollar'), ('BOB', 'BOB — Bolivian Boliviano'), ('BRL', 'BRL — Brazilian Real'), ('BSD', 'BSD — Bahamian Dollar'), ('BTN', 'BTN — Bhutanese Ngultrum'), ('BWP', 'BWP — Botswana Pula'), ('BYN', 'BYN — Belarusian Ruble'), ('BZD', 'BZD — Belize Dollar'), ('CAD', 'CAD — Canadian Dollar'), ('CDF', 'CDF — Congolese Franc'), ('CHF', 'CHF — Swiss Franc'), ('CLP', 'CLP — Chilean Peso'), ('CNY', 'CNY — Chinese Yuan'), ('COP', 'COP — Colombian Peso'), ('CRC', 'CRC — Costa Rican Colón'), ('CUP', 'CUP — Cuban Peso'), ('CVE', 'CVE — Cape Verdean Escudo'), ('CZK', 'CZK — Czech Koruna'), ('DJF', 'DJF — Djiboutian Franc'), ('DKK', 'DKK — Danish Krone'), ('DOP', 'DOP — Dominican Peso'), ('DZD', 'DZD — Algerian Dinar'), ('EGP', 'EGP — Egyptian Pound'), ('ERN', 'ERN — Eritrean Nakfa'), ('ETB', 'ETB — Ethiopian Birr'), ('EUR', 'EUR — Euro'), ('FJD', 'FJD — Fijian Dollar'), ('FKP', 'FKP — Falkland Islands Pound'), ('GBP', 'GBP — British Pound Sterling'), ('GEL', 'GEL — Georgian Lari'), ('GHS', 'GHS — Ghanaian Cedi'), ('GIP', 'GIP — Gibraltar Pound'), ('GMD', 'GMD — Gambian Dalasi'), ('GNF', 'GNF — Guinean Franc'), ('GTQ', 'GTQ — Guatemalan Quetzal'), ('GYD', 'GYD — Guyanese Dollar'), ('HKD', 'HKD — Hong Kong Dollar'), ('HNL', 'HNL — Honduran Lempira'), ('HTG', 'HTG — Haitian Gourde'), ('HUF', 'HUF — Hungarian Forint'), ('IDR', 'IDR — Indonesian Rupiah'), ('ILS', 'ILS — Israeli New Shekel'), ('INR', 'INR — Indian Rupee'), ('IQD', 'IQD — Iraqi Dinar'), ('IRR', 'IRR — Iranian Rial'), ('ISK', 'ISK — Icelandic Króna'), ('JMD', 'JMD — Jamaican Dollar'), ('JOD', 'JOD — Jordanian Dinar'), ('JPY', 'JPY — Japanese Yen'), ('KES', 'KES — Kenyan Shilling'), ('KGS', 'KGS — Kyrgyzstani Som'), ('KHR', 'KHR — Cambodian Riel'), ('KMF', 'KMF — Comorian Franc'), ('KPW', 'KPW — North Korean Won'), ('KRW', 'KRW — South Korean Won'), ('KWD', 'KWD — Kuwaiti Dinar'), ('KZT', 'KZT — Kazakhstani Tenge'), ('LAK', 'LAK — Lao Kip'), ('LBP', 'LBP — Lebanese Pound'), ('LKR', 'LKR — Sri Lankan Rupee'), ('LRD', 'LRD — Liberian Dollar'), ('LSL', 'LSL — Lesotho Loti'), ('LYD', 'LYD — Libyan Dinar'), ('MAD', 'MAD — Moroccan Dirham'), ('MDL', 'MDL — Moldovan Leu'), ('MGA', 'MGA — Malagasy Ariary'), ('MKD', 'MKD — Macedonian Denar'), ('MMK', 'MMK — Myanmar Kyat'), ('MNT', 'MNT — Mongolian Tugrik'), ('MOP', 'MOP — Macanese Pataca'), ('MRU', 'MRU — Mauritanian Ouguiya'), ('MUR', 'MUR — Mauritian Rupee'), ('MVR', 'MVR — Maldivian Rufiyaa'), ('MWK', 'MWK — Malawian Kwacha'), ('MXN', 'MXN — Mexican Peso'), ('MYR', 'MYR — Malaysian Ringgit'), ('MZN', 'MZN — Mozambican Metical'), ('NAD', 'NAD — Namibian Dollar'), ('NGN', 'NGN — Nigerian Naira'), ('NIO', 'NIO — Nicaraguan Córdoba'), ('NOK', 'NOK — Norwegian Krone'), ('NPR', 'NPR — Nepalese Rupee'), ('NZD', 'NZD — New Zealand Dollar'), ('OMR', 'OMR — Omani Rial'), ('PAB', 'PAB — Panamanian Balboa'), ('PEN', 'PEN — Peruvian Sol'), ('PGK', 'PGK — Papua New Guinean Kina'), ('PHP', 'PHP — Philippine Peso'), ('PKR', 'PKR — Pakistani Rupee'), ('PLN', 'PLN — Polish Zloty'), ('PYG', 'PYG — Paraguayan Guarani'), ('QAR', 'QAR — Qatari Riyal'), ('RON', 'RON — Romanian Leu'), ('RSD', 'RSD — Serbian Dinar'), ('RUB', 'RUB — Russian Ruble'), ('RWF', 'RWF — Rwandan Franc'), ('SAR', 'SAR — Saudi Riyal'), ('SBD', 'SBD — Solomon Islands Dollar'), ('SCR', 'SCR — Seychellois Rupee'), ('SDG', 'SDG — Sudanese Pound'), ('SEK', 'SEK — Swedish Krona'), ('SGD', 'SGD — Singapore Dollar'), ('SHP', 'SHP — Saint Helena Pound'), ('SLE', 'SLE — Sierra Leonean Leone'), ('SOS', 'SOS — Somali Shilling'), ('SRD', 'SRD — Surinamese Dollar'), ('SSP', 'SSP — South Sudanese Pound'), ('STN', 'STN — São Tomé and Príncipe Dobra'), ('SYP', 'SYP — Syrian Pound'), ('SZL', 'SZL — Eswatini Lilangeni'), ('THB', 'THB — Thai Baht'), ('TJS', 'TJS — Tajikistani Somoni'), ('TMT', 'TMT — Turkmenistani Manat'), ('TND', 'TND — Tunisian Dinar'), ('TOP', 'TOP — Tongan Paʻanga'), ('TRY', 'TRY — Turkish Lira'), ('TTD', 'TTD — Trinidad and Tobago Dollar'), ('TWD', 'TWD — New Taiwan Dollar'), ('TZS', 'TZS — Tanzanian Shilling'), ('UAH', 'UAH — Ukrainian Hryvnia'), ('UGX', 'UGX — Ugandan Shilling'), ('USD', 'USD — United States Dollar'), ('UYU', 'UYU — Uruguayan Peso'), ('UZS', 'UZS — Uzbekistani Som'), ('VES', 'VES — Venezuelan Bolívar'), ('VND', 'VND — Vietnamese Dong'), ('VUV', 'VUV — Vanuatu Vatu'), ('WST', 'WST — Samoan Tala'), ('XAF', 'XAF — Central African CFA Franc'), ('XCD', 'XCD — East Caribbean Dollar'), ('XOF', 'XOF — West African CFA Franc'), ('XPF', 'XPF — CFP Franc'), ('YER', 'YER — Yemeni Rial'), ('ZAR', 'ZAR — South African Rand'), ('ZMW', 'ZMW — Zambian Kwacha'), ('ZWL', 'ZWL — Zimbabwean Dollar')], default='BDT', help_text='Cannot be changed after first transaction is recorded.', max_length=3, verbose_name='base currency')),
                ('company_size', models.CharField(choices=[('1-10', '1–10 Employees'), ('11-50', '11–50 Employees'), ('51-200', '51–200 Employees'), ('200+', '200+ Employees')], max_length=20, verbose_name='company size')),
                ('fiscal_year_start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=7, help_text='Month number (1=January, 7=July, etc.)', verbose_name='fiscal year start month')),
                ('inventory_valuation_method', models.CharField(choices=[('FIFO', 'First In, First Out (FIFO)'), ('WEIGHTED_AVERAGE', 'Weighted Average')], default='FIFO', max_length=20, verbose_name='inventory valuation method')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='date format')),
                ('is_vds_withholding_entity', models.BooleanField(default=False, help_text='Whether this company deducts VAT at source.', verbose_name='VDS/withholding entity')),
                ('address', models.TextField(blank=True, null=True, verbose_name='street address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('country', models.CharField(default='Bangladesh', max_length=100, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='company phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('time_zone', models.CharField(default='Asia/Dhaka', max_length=50, verbose_name='time zone')),
                ('subscription_plan', models.CharField(choices=[('FREE_TRIAL', 'Free Trial'), ('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE_TRIAL', max_length=20, verbose_name='subscription plan')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='membership ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor'), ('SALES', 'Sales'), ('INVENTORY', 'Inventory')], max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='active membership')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company', verbose_name='company')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'company member',
                'verbose_name_plural': 'company members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='invited email')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('ACCOUNTANT', 'Accountant'), ('AUDITOR', 'Auditor'), ('SALES', 'Sales'), ('INVENTORY', 'Inventory')], max_length=20, verbose_name='assigned role')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='invited at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invitations', to='companies.company', verbose_name='company')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
            ],
            options={
                'verbose_name': 'pending invitation',
                'verbose_name_plural': 'pending invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='idx_company_name'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['owner'], name='idx_company_owner'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active'], name='idx_company_active'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['user', 'is_active'], name='idx_companyuser_user_active'),
        ),
        migrations.AddIndex(
            model_name='companyuser',
            index=models.Index(fields=['company', 'is_active'], name='idx_companyuser_company_active'),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('user', 'company')},
        ),
        migrations.AddIndex(
            model_name='pendinginvitation',
            index=models.Index(fields=['email', 'is_accepted'], name='idx_pending_email_accepted'),
        ),
        migrations.AlterUniqueTogether(
            name='pendinginvitation',
            unique_together={('email', 'company')},
        ),
    ]
