# Generated by Django 6.0.2 on 2026-02-24 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pendinginvitation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='companyuser',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_membership'),
        ),
        migrations.AddConstraint(
            model_name='pendinginvitation',
            constraint=models.UniqueConstraint(fields=('email', 'company'), name='unique_pending_invitation_per_company'),
        ),
    ]
