# Generated by Django 6.0.2 on 2026-03-10 07:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccounts', '0002_account_unique_active_account_name_per_classification'),
        ('companies', '0002_alter_companyuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='lock_date',
            field=models.DateField(blank=True, help_text='Transactions before this date are frozen. Only Owner/Admin can change.', null=True, verbose_name='lock date'),
        ),
        migrations.AddField(
            model_name='company',
            name='reporting_method',
            field=models.CharField(choices=[('ACCRUAL', 'Accrual'), ('CASH', 'Cash'), ('BOTH', 'Both')], default='ACCRUAL', help_text='Affects how financial reports calculate revenue/expense recognition.', max_length=10, verbose_name='reporting method'),
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "VAT 15%", "SD 5% + VAT 15%"', max_length=100, verbose_name='tax profile name')),
                ('combined_rate', models.DecimalField(decimal_places=4, help_text='Total effective rate. Pre-calculated for display.', max_digits=7, verbose_name='combined tax rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profiles', to='companies.company')),
            ],
            options={
                'verbose_name': 'tax profile',
                'verbose_name_plural': 'tax profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfileLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "VAT", "Supplementary Duty"', max_length=100, verbose_name='layer name')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax percentage for this layer.', max_digits=7, verbose_name='rate (%)')),
                ('calculation_type', models.CharField(choices=[('INDEPENDENT', 'Independent (on original amount)'), ('COMPOUND', 'Compound (on amount + previous layers)')], default='INDEPENDENT', max_length=15, verbose_name='calculation type')),
                ('apply_order', models.PositiveIntegerField(help_text='Execution order within the profile (1 = first).', verbose_name='application order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_tax_account', models.ForeignKey(help_text='Ledger account where this tax layer posts.', on_delete=django.db.models.deletion.PROTECT, related_name='tax_layer_defaults', to='chartofaccounts.account', verbose_name='default tax account')),
                ('tax_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='companies.taxprofile')),
            ],
            options={
                'verbose_name': 'tax profile layer',
                'verbose_name_plural': 'tax profile layers',
                'ordering': ['tax_profile', 'apply_order'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_code', models.CharField(help_text='ISO 4217 code (e.g., USD, EUR, GBP).', max_length=3, verbose_name='currency code')),
                ('rate_to_base', models.DecimalField(decimal_places=6, help_text='1 unit of this currency = X units of base currency.', max_digits=18, verbose_name='rate to base currency')),
                ('effective_date', models.DateField(verbose_name='effective date')),
                ('source', models.CharField(default='MANUAL', help_text='MANUAL or API provider name.', max_length=30, verbose_name='source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='companies.company')),
            ],
            options={
                'verbose_name': 'currency exchange rate',
                'verbose_name_plural': 'currency exchange rates',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('company', 'currency_code', 'effective_date'), name='unique_rate_per_currency_per_date')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(help_text='e.g., MANUAL_JOURNAL, SALES_INVOICE, PURCHASE_BILL', max_length=30, verbose_name='module name')),
                ('prefix', models.CharField(help_text='e.g., "JE-", "INV-", "BILL-"', max_length=10, verbose_name='prefix')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='next number')),
                ('padding', models.PositiveIntegerField(default=4, help_text='Number of digits. 4 → "0001", 5 → "00001".', verbose_name='zero padding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='companies.company')),
            ],
            options={
                'verbose_name': 'document sequence',
                'verbose_name_plural': 'document sequences',
                'constraints': [models.UniqueConstraint(fields=('company', 'module'), name='unique_sequence_per_company_module')],
            },
        ),
        migrations.AddConstraint(
            model_name='taxprofile',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_tax_profile_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='taxprofilelayer',
            constraint=models.UniqueConstraint(fields=('tax_profile', 'apply_order'), name='unique_layer_order_per_profile'),
        ),
    ]
