// frontend/src/components/ui/form-field.ts
//
// Type definitions and the generic FormField function for the shadcn/ui
// Form composition primitives.
//
// WHY THIS IS .ts AND NOT .tsx:
//   Vite 8's oxc parser has trouble disambiguating TypeScript generics
//   from JSX elements in .tsx files (e.g., <T> could be a generic OR a
//   JSX tag). In .ts files this ambiguity doesn't exist — TypeScript is
//   the only valid interpretation. By keeping ALL generic types here in
//   .ts, we sidestep the parser issue entirely.
//
// BEST-PRACTICE BONUS:
//   This split is a recommended pattern even without the parser quirk.
//   "Pure logic and types in .ts; rendering in .tsx" makes the codebase
//   easier to grep, easier to test, and faster for editors to type-check.
//
// THE COMPONENT IS RE-EXPORTED FROM form.tsx — your existing import
// statements `import { FormField } from '@/components/ui/form'` continue
// to work without changes.

import * as React from 'react';
import {
  Controller,
  type ControllerProps,
  type FieldPath,
  type FieldValues,
} from 'react-hook-form';

// ── FormFieldContext = which field name is currently being rendered ──
//
// Stored in React Context so that FormItem / FormLabel / FormControl /
// FormMessage can know which field they're describing without prop
// drilling. Shape is intentionally minimal (just the field name) — RHF's
// own form context provides everything else.
export type FormFieldContextValue<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
> = {
  name: TName;
};

export const FormFieldContext = React.createContext<FormFieldContextValue>(
  {} as FormFieldContextValue,
);

// ── FormItemContext = a unique id per form item ──
//
// Used to generate matching ids for label, input, description, and error
// (so screen readers know which describes which). Generated by FormItem
// via React.useId().
export type FormItemContextValue = { id: string };

export const FormItemContext = React.createContext<FormItemContextValue>(
  {} as FormItemContextValue,
);

// ── <FormField> = wraps RHF's Controller + provides field name to context ──
//
// You pass a `name` and a `render` function. The render fn gets the
// `field` object (value, onChange, onBlur, etc.) to spread on your input.
//
// Note: `function` declaration syntax (not arrow) for clean parser
// support. Same behavior either way.
export function FormField<
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
>({
  ...props
}: ControllerProps<TFieldValues, TName>) {
  return React.createElement(
    FormFieldContext.Provider,
    { value: { name: props.name } },
    React.createElement(Controller, props),
  );
}
