# Generated by Django 6.0.2 on 2026-03-10 07:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chartofaccounts', '0002_account_unique_active_account_name_per_classification'),
        ('companies', '0003_company_lock_date_company_reporting_method_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(help_text='Auto-generated. e.g., "JE-0001".', max_length=20, verbose_name='entry number')),
                ('date', models.DateField(help_text='The date the transaction financially occurred.', verbose_name='transaction date')),
                ('description', models.TextField(help_text='What is this journal entry for?', verbose_name='description')),
                ('reference', models.CharField(blank=True, help_text='Optional external reference (invoice #, receipt #, etc.).', max_length=200, null=True, verbose_name='reference')),
                ('journal_type', models.CharField(blank=True, choices=[('ADJUSTMENT', 'Adjustment'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('PAYROLL', 'Payroll'), ('DEPRECIATION', 'Depreciation'), ('INVESTMENT', 'Investment'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('OPENING_BALANCE', 'Opening Balance'), ('TRANSFER', 'Transfer'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('OTHER', 'Other')], default=None, max_length=20, null=True, verbose_name='journal type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], default='DRAFT', max_length=10, verbose_name='status')),
                ('currency', models.CharField(help_text='The main transaction currency. Defaults to company base currency.', max_length=3, verbose_name='primary currency')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate to convert journal currency to base currency.', max_digits=18, verbose_name='exchange rate')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_journals', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_journals', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('reversal_of', models.OneToOneField(blank=True, help_text='If this IS a reversing entry, points to the original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entry', to='journals.manualjournal', verbose_name='reversal of')),
                ('voided_by', models.ForeignKey(blank=True, help_text='The user who voided this entry.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_journals', to=settings.AUTH_USER_MODEL, verbose_name='voided by')),
                ('voided_by_entry', models.OneToOneField(blank=True, help_text='If voided, points to the reversing entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_voided_entry', to='journals.manualjournal', verbose_name='voided by entry')),
            ],
            options={
                'verbose_name': 'manual journal',
                'verbose_name_plural': 'manual journals',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualJournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Optional note for this specific line.', max_length=500, null=True, verbose_name='line description')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6, verbose_name='debit/credit')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in the journal currency. Always positive.', max_digits=18, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_journal_lines', to='chartofaccounts.account', verbose_name='ledger account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journals.manualjournal')),
                ('tax_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='companies.taxprofile', verbose_name='tax profile')),
            ],
            options={
                'verbose_name': 'manual journal line',
                'verbose_name_plural': 'manual journal lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='transaction date')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='note')),
                ('journal_type', models.CharField(blank=True, choices=[('ADJUSTMENT', 'Adjustment'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('PAYROLL', 'Payroll'), ('DEPRECIATION', 'Depreciation'), ('INVESTMENT', 'Investment'), ('DIVIDEND', 'Dividend'), ('TAX', 'Tax'), ('OPENING_BALANCE', 'Opening Balance'), ('TRANSFER', 'Transfer'), ('CURRENCY_EXCHANGE', 'Currency Exchange'), ('OTHER', 'Other')], default=None, help_text='Inherited from the source document header. Nullable.', max_length=20, null=True, verbose_name='journal type')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6, verbose_name='debit/credit')),
                ('currency', models.CharField(help_text="The ledger account's currency.", max_length=3, verbose_name='currency')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive. In the account currency.', max_digits=18, verbose_name='amount (account currency)')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Rate at posting time. Locked forever after posting.', max_digits=18, verbose_name='exchange rate')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Always positive. amount × exchange_rate. Snapshot at posting time.', max_digits=18, verbose_name='amount (base currency)')),
                ('source_module', models.CharField(choices=[('MANUAL_JOURNAL', 'Manual Journal'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_BILL', 'Purchase Bill'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('SYSTEM', 'System (auto-generated)')], help_text='Which module created this entry. For fast filtering.', max_length=20, verbose_name='source module')),
                ('object_id', models.UUIDField(help_text='PK of the source line record (for GenericFK).', verbose_name='source line ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='companies.company')),
                ('content_type', models.ForeignKey(help_text='ContentType of the source line model (for GenericFK).', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='source type')),
                ('ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='chartofaccounts.account', verbose_name='ledger account')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'ledger_account', 'date'], name='idx_led_comp_acc_dt'), models.Index(fields=['company', 'source_module'], name='idx_ledger_company_module'), models.Index(fields=['company', 'journal_type'], name='idx_ledger_company_jtype'), models.Index(fields=['content_type', 'object_id'], name='idx_ledger_generic_fk')],
            },
        ),
        migrations.AddIndex(
            model_name='manualjournal',
            index=models.Index(fields=['company', 'status'], name='idx_journal_company_status'),
        ),
        migrations.AddIndex(
            model_name='manualjournal',
            index=models.Index(fields=['company', 'date'], name='idx_journal_company_date'),
        ),
        migrations.AddIndex(
            model_name='manualjournal',
            index=models.Index(fields=['company', 'journal_type'], name='idx_journal_company_type'),
        ),
        migrations.AddConstraint(
            model_name='manualjournal',
            constraint=models.UniqueConstraint(fields=('company', 'entry_number'), name='unique_entry_number_per_company'),
        ),
    ]
