# Generated by Django 6.0.2 on 2026-03-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualjournal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void'), ('REVERSAL', 'Reversal')], default='DRAFT', max_length=10, verbose_name='status'),
        ),
    ]
