# Generated by Django 6.0.2 on 2026-03-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_manualjournal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='currency',
            field=models.CharField(help_text="The transaction currency (journal's currency).", max_length=3, verbose_name='currency'),
        ),
    ]
